spring:
  datasource:
    url: jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  max-http-request-header-size: 64KB
